name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 8, 11, 17, 21, 23 ]

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Choose the Java distribution (e.g., temurin, zulu, adopt)
          java-version: ${{ matrix.java-version }} # Specify the Java version (e.g., 8, 11, 17)

      # Step 3: Build the project (using Maven)
      - name: Build with Maven
        run: mvn clean package
       - name: Test with Mavne
        run: mvn test       
