name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - java-version: 8
            mandatory: true
          - java-version: 11
            mandatory: false
          - java-version: 17
            mandatory: false
          - java-version: 21
            mandatory: false
          - java-version: 23
            mandatory: false 

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      # Step 3: Build the project (using Maven)
      - name: Build with Maven
        run: mvn clean package

      - name: Mark optional JDKs as non-failing
        if: ${{ matrix.mandatory == 'false' }}
        continue-on-error: true
