name: scan

on:
  workflow_run:
    workflows: [build]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Echo location
        run: echo "GitHub Workspace: $GITHUB_WORKSPACE"

      # Step 1: Checkout the code
      - name: Scan current project
        uses: anchore/scan-action@v3
        with:
          path: "/home/runner/work/saviynt-user-custom-validation-jar/saviynt-user-custom-validation-jar/target"
